### ISSUE TITLE
can't `go get` (ring node code problems?)

### ISSUE THREAD

**Issue by 0joshuaolson1** [gholt/store#11]
`$ go get github.com/gholt/store# github.com/gholt/msgring`
```
go/src/github.com/gholt/msgring/tcp_msg_ring.go:267:10: n.Address undefined (type *ring.Node has no field or method Address)
go/src/github.com/gholt/msgring/tcp_msg_ring.go:312:10: cannot convert nil to type ring.Ring
go/src/github.com/gholt/msgring/tcp_msg_ring.go:317:14: ring.Node undefined (type ring.Ring has no field or method Node)
go/src/github.com/gholt/msgring/tcp_msg_ring.go:338:10: cannot convert nil to type ring.Ring
go/src/github.com/gholt/msgring/tcp_msg_ring.go:343:15: ring.ResponsibleNodes undefined (type ring.Ring has no field or method ResponsibleNodes)
go/src/github.com/gholt/msgring/tcp_msg_ring.go:351:22: ring.LocalNode undefined (type ring.Ring has no field or method LocalNode)
go/src/github.com/gholt/msgring/tcp_msg_ring.go:401:11: cannot convert nil to type ring.Ring
go/src/github.com/gholt/msgring/tcp_msg_ring.go:405:15: ring.LocalNode undefined (type ring.Ring has no field or method LocalNode)
go/src/github.com/gholt/msgring/tcp_msg_ring.go:554:26: t.Ring().LocalNode undefined (type ring.Ring has no field or method LocalNode)
go/src/github.com/gholt/msgring/tcp_msg_ring.go:601:24: t.Ring().Node undefined (type ring.Ring has no field or method Node)
go/src/github.com/gholt/msgring/tcp_msg_ring.go:601:24: too many errors
```

**Comment by gholt** [comment]
Ah yes, I'm sorry for that. The whole thing (store, msgring, etc.) was an R&D project that was abandoned about a year ago, but the ring code has diverged since then.

Hopefully I can get some time to at least bring it up to date with itself again.

Until then, if you are really interested in playing around with the code, you can `git checkout edcf6548afeea9de7f40b0c39f55018369d7524a` in the github.com/gholt/ring repository and it should all compile again. That was just before the ring package refactoring.

**Comment by gholt** [comment]
Okay, I created a github.com/gholt/devicering repo for now that is the code from the ring repo at the point mentioned above.

Someday I hope to work on this project again and update it to work with the new ring code.
