### ISSUE TITLE
Write then Lookup returns ErrNotFound

### ISSUE THREAD

**Issue by 0joshuaolson1** [gholt/store#12]
Am I doing something wrong?
```
package main
import(
  DB "github.com/gholt/store"
  //"context" <- no change with a non-nil context
  "fmt"
)
func main(){
  db, _ := DB.NewValueStore(nil) // no change with a non-nil *ValueStoreConfig
  db.Write(nil, 3, 932220, 0, nil) // no change with a non-nil []byte
  t, m, e := db.Lookup(nil, 3, 932220)
  fmt.Println(t, m, DB.IsNotFound(e)) // 0, 0, true
}
```

**Comment by gholt** [comment]
Hi, just back from a week of vacation...

There are a couple of things here:

The Write call was returning an error indicating that the timestamp given (0 in this case) was less than 256, so the write was never happening. There is a lot of documentation so it takes a while to absorb it all. :) Relevant section for why 256 is the minimum:

> Internally, each modification is stored with a uint64 timestamp that is equivalent to (brimtime.TimeToUnixMicro(time.Now())<<8) with the lowest 8 bits used to indicate deletions and other bookkeeping items. This means that the allowable time range is 1970-01-01 00:00:00 +0000 UTC (+1 microsecond because all zeroes indicates a missing item) to 4253-05-31 22:20:37.927935 +0000 UTC. There are constants TIMESTAMPMICRO_MIN and TIMESTAMPMICRO_MAX available for bounding usage.

So, if we change that timestampmicro to 256, we'll then get a new issue, which is a divide by zero panic. Granted, this could be much improved to return a proper error about what is wrong, but this is all fairly raw code. :) The issue here is that the ValueStore was created but never started (by calling Startup).

So, the example should end up as:

```
package main

import (
    DB "github.com/gholt/store"
    //"context" <- no change with a non-nil context
    "fmt"
)

func main() {
    db, _ := DB.NewValueStore(nil) // no change with a non-nil *ValueStoreConfig
    e := db.Startup(nil)
    if e != nil {
        panic(e)
    }
    _, e = db.Write(nil, 3, 932220, 256, nil) // no change with a non-nil []byte
    if e != nil {
        panic(e)
    }
    t, m, e := db.Lookup(nil, 3, 932220)
    fmt.Println(t, m, DB.IsNotFound(e)) // 0, 0, true
}
```

And you'll get the output of:

```
256 0 false
```

**Comment by 0joshuaolson1** [comment]
Dang, I missed `Startup` in the docs. Thanks!
